apiVersion: v1
kind: Service
metadata:
  name: rabbit
  labels:
    app: hawkbit
    name: rabbit
spec:
  ports:
  - name: epmd
    port: 4369
    targetPort: epmd
  - name: amqp
    port: 5672
    targetPort: amqp
  - name: dist
    port: 25672
    targetPort: dist
  - name: stats
    port: 15672
    targetPort: stats
  selector:
    app: hawkbit
    name: rabbit
