apiVersion: v1
kind: Secret
metadata:
  name: hawkbit
  labels:
    app: hawkbit
type: Opaque
stringData:
  SPRING_APPLICATION_JSON: |-
   {
     "hawkbit":{
       "dmf":{
         "hono":{
           "password":"[KEYCLOAK_HAWKBIT_USER_PASSWORD]"
         }
       }
     },
     "spring":{
       "security":{
         "user":{
           "password":"{noop}admin"
         }
       }
     }
   }
