apiVersion: v1
kind: Service
metadata:
  name: hawkbit-lb
  labels:
    app: hawkbit
spec:
  type: LoadBalancer
  selector:
    app: hawkbit
    name: hawkbit
  ports:
    - port: 80
      targetPort: http
      name: http
      protocol: TCP
