apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: hawkbit
    name: mysql
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    name: mysql
    app: hawkbit
